name: React App CI/CD

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout/Get Code
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm ci
      - name: Lint
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout/Get Code
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm ci
      - name: Test
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
    - name: Checkout/Get Code
      uses: actions/checkout@v3
    - name: Install Dependencies
      run: npm ci
    - name: Build
      run: npm run build
    - name: Deploy Code
      run: echo "Deploying..."

   